# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import contest_pb2 as contest__pb2


class ContestDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetContestData = channel.unary_unary(
                '/ContestDataService/GetContestData',
                request_serializer=contest__pb2.ContestDataRequest.SerializeToString,
                response_deserializer=contest__pb2.ContestData.FromString,
                )


class ContestDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetContestData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContestDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetContestData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContestData,
                    request_deserializer=contest__pb2.ContestDataRequest.FromString,
                    response_serializer=contest__pb2.ContestData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ContestDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ContestDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetContestData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ContestDataService/GetContestData',
            contest__pb2.ContestDataRequest.SerializeToString,
            contest__pb2.ContestData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
