# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='contest.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rcontest.proto\"\xa3\x01\n\x0b\x43ontestData\x12\x0e\n\x06handle\x18\x01 \x01(\t\x12\x13\n\x0bprofile_url\x18\x02 \x01(\t\x12&\n\x08\x63ontests\x18\x03 \x03(\x0b\x32\x14.ContestData.Contest\x1aG\n\x07\x43ontest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x05\x12\x0e\n\x06rating\x18\x04 \x01(\x05\"6\n\x12\x43ontestDataRequest\x12\x10\n\x08platform\x18\x01 \x01(\t\x12\x0e\n\x06handle\x18\x02 \x01(\t2I\n\x12\x43ontestDataService\x12\x33\n\x0eGetContestData\x12\x13.ContestDataRequest\x1a\x0c.ContestDatab\x06proto3'
)




_CONTESTDATA_CONTEST = _descriptor.Descriptor(
  name='Contest',
  full_name='ContestData.Contest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ContestData.Contest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='ContestData.Contest.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ContestData.Contest.timestamp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rating', full_name='ContestData.Contest.rating', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=181,
)

_CONTESTDATA = _descriptor.Descriptor(
  name='ContestData',
  full_name='ContestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='handle', full_name='ContestData.handle', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='profile_url', full_name='ContestData.profile_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contests', full_name='ContestData.contests', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CONTESTDATA_CONTEST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=181,
)


_CONTESTDATAREQUEST = _descriptor.Descriptor(
  name='ContestDataRequest',
  full_name='ContestDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='platform', full_name='ContestDataRequest.platform', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='handle', full_name='ContestDataRequest.handle', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=237,
)

_CONTESTDATA_CONTEST.containing_type = _CONTESTDATA
_CONTESTDATA.fields_by_name['contests'].message_type = _CONTESTDATA_CONTEST
DESCRIPTOR.message_types_by_name['ContestData'] = _CONTESTDATA
DESCRIPTOR.message_types_by_name['ContestDataRequest'] = _CONTESTDATAREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContestData = _reflection.GeneratedProtocolMessageType('ContestData', (_message.Message,), {

  'Contest' : _reflection.GeneratedProtocolMessageType('Contest', (_message.Message,), {
    'DESCRIPTOR' : _CONTESTDATA_CONTEST,
    '__module__' : 'contest_pb2'
    # @@protoc_insertion_point(class_scope:ContestData.Contest)
    })
  ,
  'DESCRIPTOR' : _CONTESTDATA,
  '__module__' : 'contest_pb2'
  # @@protoc_insertion_point(class_scope:ContestData)
  })
_sym_db.RegisterMessage(ContestData)
_sym_db.RegisterMessage(ContestData.Contest)

ContestDataRequest = _reflection.GeneratedProtocolMessageType('ContestDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONTESTDATAREQUEST,
  '__module__' : 'contest_pb2'
  # @@protoc_insertion_point(class_scope:ContestDataRequest)
  })
_sym_db.RegisterMessage(ContestDataRequest)



_CONTESTDATASERVICE = _descriptor.ServiceDescriptor(
  name='ContestDataService',
  full_name='ContestDataService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=239,
  serialized_end=312,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetContestData',
    full_name='ContestDataService.GetContestData',
    index=0,
    containing_service=None,
    input_type=_CONTESTDATAREQUEST,
    output_type=_CONTESTDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTESTDATASERVICE)

DESCRIPTOR.services_by_name['ContestDataService'] = _CONTESTDATASERVICE

# @@protoc_insertion_point(module_scope)
