# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import submit_pb2 as submit__pb2


class SubmitDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSubmitData = channel.unary_unary(
                '/SubmitDataService/GetSubmitData',
                request_serializer=submit__pb2.SubmitDataRequest.SerializeToString,
                response_deserializer=submit__pb2.SubmitData.FromString,
                )


class SubmitDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSubmitData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SubmitDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSubmitData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubmitData,
                    request_deserializer=submit__pb2.SubmitDataRequest.FromString,
                    response_serializer=submit__pb2.SubmitData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SubmitDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SubmitDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSubmitData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SubmitDataService/GetSubmitData',
            submit__pb2.SubmitDataRequest.SerializeToString,
            submit__pb2.SubmitData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
